### ISSUE TITLE
ios9 issue

### ISSUE THREAD

**Issue by oggyindahouse** [peutetre/cordova-plugin-hockeyapp#10]
I can not build in XCODE for IOS 9. This plugin includes as given HockeyAppSDK-iOS 3.7.1. 
Hockey SDK 3.8+ supports ios9 accordung to release notes hier: http://hockeyapp.net/help/sdk/ios/3.8.2/docs/docs/Changelog.html

**Comment by peutetre** [comment]
done in version 1.2.0 see https://github.com/peutetre/cordova-plugin-hockeyapp#warning for iOS 9
