### ISSUE TITLE
Visual Studio 2015 Cordova Plugin Add Fail

### ISSUE THREAD

**Issue by SergeyA** [peutetre/cordova-plugin-hockeyapp#12]
I get error when trying to add this plugin to Visual Studio Tools For Apache Cordova: 
"Visual Studio was unable to parse plugin.xml. Please ensure plugin.xml exists and contains no errors."
It is caused by a missing declaration for "android" namespace. 

    <plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
        xmlns:android="http://schemas.android.com/apk/res/android" <-- missing namespace
        id="cordova-plugin-hockeyapp"
        version="1.3.0">

**Comment by peutetre** [comment]
1.3.1 is released on npm
