### ISSUE TITLE
Adding details to crash report

### ISSUE THREAD

**Issue by jskrepnek** [peutetre/cordova-plugin-hockeyapp#19]
Hi,

Is there a mechanism for supplying crash details manually?  In the case of an unhandled exception in the WebView I would like to force a crash and pass details on to HockeyApp.

**Comment by piotrowski** [comment]
Do you really want to crash the app for the user? 

You could probably adapt the crash function so it contains some information about the JS exception that is then displayed at HockeyApp.

**Comment by jskrepnek** [comment]
Thanks.
