### ISSUE TITLE
Suggestion: Automatically ENABLE_BITCODE=NO via plugin hook for Cordova iOS < 3.9.2

### ISSUE THREAD

**Issue by Chuxel** [peutetre/cordova-plugin-hockeyapp#21]
The message about ENABLE_BITCODE for iOS is a bit misleading since this is only true if you are using Cordova < 5.2.0 - specifically Cordova iOS platform versions < 3.9.2 (which was released in Nov but is installed by 5.2.0 and 5.3.3).  New versions of the iOS platform also won't have this problem.

A better solution would be to simply append the ENABLE_BITCODE=NO setting if not found via a cordova hook. 

Generally checking in the platforms folder into source control isn't supposed to be required, but this sort of forces you to do so.

**Comment by piotrowski** [comment]
Here is an easy hook that support setting `ENABLE_BITCODE = NO`: https://github.com/mhartington/cordova-config-utils Here you can see how you config it to do so in your config.xml: https://github.com/mhartington/cordova-config-utils#ios

Question is, how should this really be integrated into this plugin without any side effects? Can you do something like that in plugin.xml?

**Comment by Chuxel** [comment]
Given it's a requirement for the plugin to function, you'd need to set it regardless of impacts or side effects... it needs to be NO for it to work with Xcode 7. I think you can use the same XML shown in the plugin above in plugin.xml.  Failing that, you could make the above plugin a dependency and add the preference elements to config.xml in plugin.xml or write a simple hook that uses shelljs to add the setting to platforms/ios/cordova/build.xconfig

**Comment by peutetre** [comment]
fixed in 2.1.0
