### ISSUE TITLE
[Android] hockeyapp.checkForUpdate return value

### ISSUE THREAD

**Issue by DFranch** [peutetre/cordova-plugin-hockeyapp#25]
Hi guys,

I am trying to integrate this plugin in my Ionic app.
My question is regarding the `hockeyapp.checkForUpdate()` function. When outputting the result in the logcat 
```JavaScript
hockeyapp.checkForUpdate(function (success) {
  console.log(JSON.stringify(success));
}, function (error) {
  console.log(JSON.stringify(error));
})
```
The response is
```bash
I/chromium( 3384): [INFO:CONSOLE(38)] ""OK"", source: file:///android_asset/www/app/app.js (38)
```

I would like to show a "There is a new update" dialog if there is a new update.
How can I detect if there is a new update if the plugin only returns "OK"?

**Comment by peutetre** [comment]
you will get a native popup when an update is available

**Comment by DFranch** [comment]
Okay, I didn't notice this from the documentation - Thank you for clarifying.
