### ISSUE TITLE
crashes not logged in hockeyapp dashboard for ios

### ISSUE THREAD

**Issue by laylaaitlaaraj** [peutetre/cordova-plugin-hockeyapp#5]
Hi,

I’m working on the integration of hockey sdk in a hybrid application. For that I’m using cordova-plugin-hockeyapp https://github.com/peutetre/cordova-plugin-hockeyapp

Android version works fine, crashed are detected and sent to the hockey dashboard, but for iOS the app crashes but the next time i launch it there is no popup shown and thus no crashes are logged in the hockeyapp dashboard.

Here are sdk i have in my project : (no 3rd party that has a crash reporting feature)
![screen shot 2015-07-08 at 11 02 28](https://cloud.githubusercontent.com/assets/11313327/8570569/1fe7ea24-2579-11e5-90b1-13b0e6a14dcf.png)

When a crash occurs in the app installed from hockeyapp plateform, the next time i launch a clean app no popup shown asking the user whether he wants to send crash log to the server or not. Thus no crashes are logged in hockeyapp dashboard.

Thanx in advance for your help.

Best

**Comment by peutetre** [comment]
Fixed in version 1.1.6 (usage example https://github.com/peutetre/example-cordova-plugin-hockeyapp with tarifa)

**Comment by gigeos** [comment]
Hi,

I have the same problem with version 5.1.2. I build app on iOS and Android device from my Mac, and event and crashed are logged. All is fine.
Then I install app in release mode from private store, and all is good for Android and events are reported for iOS. But not the crashes. (I use `forceCrash()`function. )
