### ISSUE TITLE
Support for iOS 9 - include bitcode

### ISSUE THREAD

**Issue by craig-at-rsg** [peutetre/cordova-plugin-hockeyapp#6]
iOS 9 builds require bitcode by default. It's possible to set ENABLE_BITCODE to NO, but this isn't the recommended setting, and it isn't easy to do with the Cordova CLI (my project rebuilds the platforms directory often, so doing this manually with XCode is not a good option). 

Could you please include the bitcode for hockeyapp so the ENABLE_BITCODE default can be used?

**Comment by peutetre** [comment]
currently the plugin just imports the hockeyapp static library which does not support bitcode. I will wait until a new release from hockeyapp

**Comment by craig-at-rsg** [comment]
Here's the source: https://github.com/bitstadium/HockeySDK-iOS

**Comment by peutetre** [comment]
Now you can do a pull request ;-)

**Comment by craig-at-rsg** [comment]
Asked HockeyApp - they say it isn't possible yet:

> right now we can't, since we need PLCrashReporter with Bitcode support, and that is also not released. We might release a beta version before Xcode 7 GM is available, but this isn't for sure.
